sensor:

  - platform: darksky
    api_key: !secret darksky
    forecast:
      - 0
    hourly_forecast:
      - 12
    monitored_conditions:
      - summary
      - icon
      - temperature
      - precip_probability
      - precip_intensity
      - sunrise_time
      - sunset_time
    scan_interval:
      minutes: 30

  - platform: time_date
    display_options:
      - 'time'

  - platform: time_date
    display_options:
      - 'date'

  - platform: knx
    name: Helligkeit Süd
    state_address: '0/1/0'
    type: 'illuminance'
    
  - platform: knx
    name: Dämmerung
    state_address: '0/1/1'
    type: 'illuminance'
    
  - platform: knx
    name: Wind
    state_address: '0/1/2'
    type: 'speed_ms'
    
  - platform: knx
    name: Aussentemperatur
    state_address: '0/1/3'
    type: 'temperature'
    
  - platform: knx
    name: Helligkeit Speis
    state_address: '0/1/4'
    type: 'illuminance'
    
  - platform: knx
    name: Helligkeit Abstellraum
    state_address: '0/1/5'
    type: 'illuminance'
    
  - platform: knx
    name: Helligkeit Flur EG
    state_address: '0/1/6'
    type: 'illuminance'
    
  - platform: knx
    name: Helligkeit Bad EG
    state_address: '0/1/7'
    type: 'illuminance'
    
  - platform: knx
    name: Helligkeit Wohnzimmer
    state_address: '0/1/8'
    type: 'illuminance'
    
  - platform: knx
    name: Helligkeit Essbereich
    state_address: '0/1/9'
    type: 'illuminance'
    
  - platform: knx
    name: Helligkeit Stiege
    state_address: '0/1/10'
    type: 'illuminance'
    
  - platform: knx
    name: Helligkeit Zimmer
    state_address: '0/1/11'
    type: 'illuminance'
    
  - platform: knx
    name: Helligkeit Büro
    state_address: '0/1/12'
    type: 'illuminance'   
    
  - platform: knx
    name: Helligkeit Ankleide
    state_address: '0/1/13'
    type: 'illuminance'   
    
  - platform: knx
    name: Helligkeit WC OG
    state_address: '0/1/14'
    type: 'illuminance' 
    
  - platform: knx
    name: Helligkeit Bad OG
    state_address: '0/1/15'
    type: 'illuminance'
    
  - platform: knx
    name: Helligkeit Flur OG
    state_address: '0/1/16'
    type: 'illuminance'
    
  - platform: knx
    name: Helligkeit Schlaf
    state_address: '0/1/17'
    type: 'illuminance'
    
  - platform: knx
    name: Helligkeit Schlaf2
    state_address: '0/1/18'
    type: 'illuminance'
  
